ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "signature" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "headerLanguageMode" TEXT NOT NULL DEFAULT 'FR_ONLY';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "arabicCountry" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "arabicName" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "arabicMinistry" TEXT;
