ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "secondaryStamp" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "thirdStamp" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "arabicMotto" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "contactPlacement" TEXT NOT NULL DEFAULT 'BOTTOM';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "sealSizeMm" INTEGER NOT NULL DEFAULT 35;
